export interface NumberQuestion {
  id: string;
  question: string;
  answer: number;
  unit: string;
  category: '지리' | '과학' | '스포츠' | '생활' | '문화' | '음식';
  explanation: string;
}

export const NUMBER_QUESTIONS: NumberQuestion[] = [
  {
    id: 'everest-height',
    question: '2020년 네팔과 중국이 공동 발표한 에베레스트의 높이는?',
    answer: 8848.86,
    unit: 'm',
    category: '지리',
    explanation: '2020년 공동 측량에서 발표한 눈 덮인 정상의 공식 해발 고도입니다.',
  },
  {
    id: 'fuji-height',
    question: '일본에서 가장 높은 산인 후지산의 높이는?',
    answer: 3776,
    unit: 'm',
    category: '지리',
    explanation: '일본정부관광국이 안내하는 후지산의 해발 고도입니다.',
  },
  {
    id: 'eiffel-height',
    question: '2022년 새 안테나 설치 후 에펠탑의 전체 높이는?',
    answer: 330,
    unit: 'm',
    category: '지리',
    explanation: '2022년 6m 높이의 안테나가 추가된 뒤 공식 높이는 330m가 되었습니다.',
  },
  {
    id: 'challenger-deep',
    question: 'NOAA가 안내하는 마리아나 해구 챌린저 해연의 깊이는 약 얼마일까?',
    answer: 10935,
    unit: 'm',
    category: '지리',
    explanation: 'NOAA가 최근 다중빔 자료를 바탕으로 제시한 근사 깊이입니다.',
  },
  {
    id: 'moon-distance',
    question: '지구에서 달까지의 평균 거리는?',
    answer: 384400,
    unit: 'km',
    category: '과학',
    explanation: 'NASA가 사용하는 지구와 달 사이의 평균 거리입니다.',
  },
  {
    id: 'earth-sun-distance',
    question: '지구에서 태양까지의 평균 거리는 약 얼마일까?',
    answer: 150000000,
    unit: 'km',
    category: '과학',
    explanation: 'NASA가 안내하는 평균 거리 약 1억 5천만 km를 기준으로 합니다.',
  },
  {
    id: 'speed-of-light',
    question: '진공에서 빛의 속도는 초당 몇 m일까?',
    answer: 299792458,
    unit: 'm/s',
    category: '과학',
    explanation: '국제단위계에서 정확히 고정해 사용하는 빛의 속도입니다.',
  },
  {
    id: 'ocean-average-depth',
    question: '전 세계 바다의 평균 깊이는 약 얼마일까?',
    answer: 3682,
    unit: 'm',
    category: '과학',
    explanation: '미국 해양대기청(NOAA)이 제시하는 전 세계 바다의 평균 깊이입니다.',
  },
  {
    id: 'marathon-distance',
    question: '정식 마라톤 코스의 거리는?',
    answer: 42.195,
    unit: 'km',
    category: '스포츠',
    explanation: '세계육상연맹이 정한 표준 마라톤 거리입니다.',
  },
  {
    id: 'football-goal-width',
    question: '성인 축구 골대 양쪽 기둥 안쪽 사이의 너비는?',
    answer: 7.32,
    unit: 'm',
    category: '스포츠',
    explanation: '국제축구평의회 경기 규칙에 명시된 골대 너비입니다.',
  },
  {
    id: 'football-goal-height',
    question: '성인 축구 골대의 지면부터 크로스바 아래까지 높이는?',
    answer: 2.44,
    unit: 'm',
    category: '스포츠',
    explanation: '국제축구평의회 경기 규칙에 명시된 골대 높이입니다.',
  },
  {
    id: 'tennis-court-length',
    question: '국제 규격 테니스 코트의 세로 길이는?',
    answer: 23.77,
    unit: 'm',
    category: '스포츠',
    explanation: '국제테니스연맹 규칙의 78피트를 미터로 표시한 값입니다.',
  },
  {
    id: 'olympic-pool-length',
    question: '올림픽 경영 종목에 사용되는 롱코스 수영장의 길이는?',
    answer: 50,
    unit: 'm',
    category: '스포츠',
    explanation: '올림픽 경영 종목에서 사용하는 롱코스 수영장 규격입니다.',
  },
  {
    id: 'basketball-hoop-height',
    question: '농구 골대 림의 지면으로부터 높이는?',
    answer: 3.05,
    unit: 'm',
    category: '스포츠',
    explanation: '국제 농구 규격의 10피트를 미터로 나타낸 값입니다.',
  },
  {
    id: 'volleyball-court-length',
    question: '국제 규격 배구 코트의 세로 길이는?',
    answer: 18,
    unit: 'm',
    category: '스포츠',
    explanation: '국제 배구 경기장에서 사용하는 코트 규격은 18m × 9m입니다.',
  },
  {
    id: 'badminton-court-length',
    question: '국제 규격 배드민턴 코트의 세로 길이는?',
    answer: 13.4,
    unit: 'm',
    category: '스포츠',
    explanation: '배드민턴 경기 규칙에 따른 전체 코트의 세로 길이입니다.',
  },
  {
    id: 'table-tennis-table-length',
    question: '국제 규격 탁구대의 길이는?',
    answer: 2.74,
    unit: 'm',
    category: '스포츠',
    explanation: '국제 탁구 규격의 9피트를 미터로 표시한 값입니다.',
  },
  {
    id: 'a4-area',
    question: 'A4 용지 한 장의 넓이는?',
    answer: 623.7,
    unit: 'cm²',
    category: '생활',
    explanation: 'ISO 216 규격 21cm × 29.7cm를 곱한 값입니다.',
  },
  {
    id: 'leap-year-hours',
    question: '윤년 1년은 총 몇 시간일까?',
    answer: 8784,
    unit: '시간',
    category: '생활',
    explanation: '윤년의 366일에 하루 24시간을 곱한 값입니다.',
  },
  {
    id: 'water-liter-weight',
    question: '4℃의 순수한 물 1L의 질량은 약 얼마일까?',
    answer: 1,
    unit: 'kg',
    category: '생활',
    explanation: '물의 밀도가 가장 높은 4℃ 부근에서 1L는 약 1kg입니다.',
  },
  {
    id: 'burj-khalifa-height',
    question: '두바이 부르즈 할리파의 공식 높이는?',
    answer: 828,
    unit: 'm',
    category: '지리',
    explanation: '부르즈 할리파 공식 자료에 명시된 최종 높이입니다.',
  },
  {
    id: 'statue-of-liberty-height',
    question: '지면에서 횃불 끝까지 잰 자유의 여신상의 전체 높이는?',
    answer: 92.99,
    unit: 'm',
    category: '지리',
    explanation: '미국 국립공원관리청이 안내하는 지면부터 횃불 끝까지의 높이입니다.',
  },
  {
    id: 'elizabeth-tower-height',
    question: '영국 국회의사당 엘리자베스 타워(빅벤 시계탑)의 높이는?',
    answer: 96,
    unit: 'm',
    category: '지리',
    explanation: '영국 의회가 공개한 엘리자베스 타워의 높이입니다.',
  },
  {
    id: 'golden-gate-bridge-length',
    question: '진입 구간을 포함한 금문교의 전체 길이는?',
    answer: 2737,
    unit: 'm',
    category: '지리',
    explanation: '금문교 관리 기관이 공개한 교대부터 교대까지의 전체 길이입니다.',
  },
  {
    id: 'tokyo-skytree-height',
    question: '일본 도쿄 스카이트리의 높이는?',
    answer: 634,
    unit: 'm',
    category: '지리',
    explanation: '도쿄 스카이트리 공식 사이트가 안내하는 최고 높이입니다.',
  },
  {
    id: 'n-seoul-tower-height',
    question: '남산 높이를 제외한 N서울타워 자체의 높이는?',
    answer: 236.7,
    unit: 'm',
    category: '지리',
    explanation: '서울 공식 관광 안내에 명시된 타워 자체의 높이입니다.',
  },
  {
    id: 'lotte-world-tower-height',
    question: '서울 잠실 롯데월드타워의 높이는?',
    answer: 555,
    unit: 'm',
    category: '지리',
    explanation: '롯데건설이 공개한 지상 123층 롯데월드타워의 높이입니다.',
  },
  {
    id: 'grand-canyon-length',
    question: '미국 국립공원관리청 기준 그랜드캐니언의 길이는 약 얼마일까?',
    answer: 446,
    unit: 'km',
    category: '지리',
    explanation: '콜로라도강의 흐름을 따라 측정한 약 277마일의 길이입니다.',
  },
  {
    id: 'gateway-arch-height',
    question: '미국 세인트루이스 게이트웨이 아치의 높이는?',
    answer: 192,
    unit: 'm',
    category: '지리',
    explanation: '미국 국립공원관리청이 안내하는 게이트웨이 아치의 높이입니다.',
  },
  {
    id: 'washington-monument-height',
    question: '미국 워싱턴 기념탑의 높이는 약 얼마일까?',
    answer: 169,
    unit: 'm',
    category: '지리',
    explanation: '미국 국립공원관리청이 안내하는 기념탑의 높이입니다.',
  },
  {
    id: 'mount-rushmore-washington-head-height',
    question: '러시모어산에 조각된 조지 워싱턴 얼굴의 높이는?',
    answer: 18.3,
    unit: 'm',
    category: '문화',
    explanation: '미국 국립공원관리청이 공개한 머리 전체의 높이입니다.',
  },
  {
    id: 'sydney-opera-house-height',
    question: '시드니 오페라하우스의 가장 높은 지붕은 해수면에서 몇 m 높이일까?',
    answer: 67,
    unit: 'm',
    category: '문화',
    explanation: '시드니 오페라하우스 공식 관광 자료의 최고 지붕 높이입니다.',
  },
  {
    id: 'earth-equatorial-diameter',
    question: '지구의 적도 지름은 약 얼마일까?',
    answer: 12756,
    unit: 'km',
    category: '과학',
    explanation: 'NASA가 안내하는 지구의 적도 지름입니다.',
  },
  {
    id: 'sunlight-to-earth-time',
    question: '태양빛이 지구까지 오는 데 걸리는 시간은 약 얼마일까?',
    answer: 8.35,
    unit: '분',
    category: '과학',
    explanation: 'NASA가 제시하는 태양에서 지구까지의 편도 빛 이동 시간입니다.',
  },
  {
    id: 'moon-diameter',
    question: '달의 지름은 약 얼마일까?',
    answer: 3475,
    unit: 'km',
    category: '과학',
    explanation: 'NASA 달 자료에 제시된 평균적인 지름입니다.',
  },
  {
    id: 'moon-orbit-period',
    question: '달이 지구를 한 바퀴 공전하는 데 걸리는 시간은?',
    answer: 27.32,
    unit: '일',
    category: '과학',
    explanation: 'NASA가 제시하는 달의 항성 공전 주기입니다.',
  },
  {
    id: 'lunar-phase-cycle',
    question: '달의 모양이 삭에서 다음 삭까지 한 주기를 도는 데 걸리는 시간은 약 얼마일까?',
    answer: 29.5,
    unit: '일',
    category: '과학',
    explanation: 'NASA가 안내하는 달의 위상 변화 한 주기 길이입니다.',
  },
  {
    id: 'sun-diameter',
    question: '태양의 지름은 약 얼마일까?',
    answer: 1400000,
    unit: 'km',
    category: '과학',
    explanation: 'NASA가 안내하는 태양의 근사 지름입니다.',
  },
  {
    id: 'sun-surface-temperature',
    question: '태양의 눈에 보이는 표면 온도는 약 몇 ℃일까?',
    answer: 5500,
    unit: '℃',
    category: '과학',
    explanation: 'NASA가 안내하는 태양 광구의 근사 온도입니다.',
  },
  {
    id: 'sun-core-temperature',
    question: '태양 중심부의 온도는 약 몇 ℃일까?',
    answer: 15000000,
    unit: '℃',
    category: '과학',
    explanation: 'NASA가 안내하는 태양 핵의 근사 온도입니다.',
  },
  {
    id: 'mars-day-length',
    question: '화성의 하루는 지구 시간으로 약 몇 시간일까?',
    answer: 24.7,
    unit: '시간',
    category: '과학',
    explanation: 'NASA가 사용하는 화성 태양일의 근사 길이입니다.',
  },
  {
    id: 'mars-year-length',
    question: '화성이 태양을 한 바퀴 도는 데 걸리는 지구 날짜는?',
    answer: 687,
    unit: '일',
    category: '과학',
    explanation: 'NASA가 안내하는 화성의 1년 길이입니다.',
  },
  {
    id: 'jupiter-day-length',
    question: '목성의 하루는 약 몇 시간일까?',
    answer: 9.9,
    unit: '시간',
    category: '과학',
    explanation: 'NASA가 안내하는 목성의 자전 주기입니다.',
  },
  {
    id: 'jupiter-year-length',
    question: '목성이 태양을 한 바퀴 도는 데 걸리는 지구 날짜는 약 얼마일까?',
    answer: 4333,
    unit: '일',
    category: '과학',
    explanation: 'NASA가 안내하는 목성의 공전 주기 약 12지구년을 일수로 표시한 값입니다.',
  },
  {
    id: 'venus-surface-temperature',
    question: '금성의 평균적인 표면 온도는 약 몇 ℃일까?',
    answer: 467,
    unit: '℃',
    category: '과학',
    explanation: 'NASA가 안내하는 금성 표면의 근사 온도입니다.',
  },
  {
    id: 'mercury-year-length',
    question: '수성이 태양을 한 바퀴 도는 데 걸리는 지구 날짜는?',
    answer: 88,
    unit: '일',
    category: '과학',
    explanation: 'NASA가 안내하는 수성의 공전 주기입니다.',
  },
  {
    id: 'shin-ramyun-calories',
    question: '농심 신라면 봉지면 1개(120g)의 열량은?',
    answer: 500,
    unit: 'kcal',
    category: '음식',
    explanation: '농심 공식 제품 정보에 표시된 신라면 봉지면 1개 기준 열량입니다.',
  },
  {
    id: 'shin-ramyun-cooking-water',
    question: '농심 공식 조리법에서 신라면 봉지면 1개에 넣는 물의 양은?',
    answer: 550,
    unit: 'ml',
    category: '음식',
    explanation: '농심 공식 조리법에 안내된 봉지면 1개 기준 물의 양입니다.',
  },
  {
    id: 'boeing-7478-length',
    question: '보잉 747-8 항공기의 전체 길이는?',
    answer: 76.2,
    unit: 'm',
    category: '과학',
    explanation: '보잉이 공개한 747-8의 전체 길이입니다.',
  },
  {
    id: 'airbus-a380-max-seats',
    question: '에어버스 A380의 인증된 최대 좌석 수는?',
    answer: 853,
    unit: '석',
    category: '과학',
    explanation: '에어버스가 공개한 올 이코노미 구성 기준 최대 인증 좌석 수입니다.',
  },
  {
    id: 'concorde-top-speed',
    question: '초음속 여객기 콩코드의 최고 속도는 약 시속 몇 km일까?',
    answer: 2179,
    unit: 'km/h',
    category: '과학',
    explanation: '미국 국립항공우주박물관이 제시하는 콩코드의 최고 속도입니다.',
  },
  {
    id: 'iss-length',
    question: '태양전지판을 가로지르는 국제우주정거장(ISS)의 전체 길이는?',
    answer: 109,
    unit: 'm',
    category: '과학',
    explanation: 'NASA가 공개한 국제우주정거장의 끝에서 끝까지 길이입니다.',
  },
  {
    id: 'iss-speed',
    question: '국제우주정거장(ISS)은 약 시속 몇 km로 지구를 돌까?',
    answer: 28000,
    unit: 'km/h',
    category: '과학',
    explanation: 'NASA가 안내하는 국제우주정거장의 근사 궤도 속도입니다.',
  },
  {
    id: 'fiba-game-minutes',
    question: 'FIBA 농구 정규 경기의 실제 경기 시간은 총 몇 분일까?',
    answer: 40,
    unit: '분',
    category: '스포츠',
    explanation: 'FIBA 규칙의 10분씩 4쿼터를 합한 경기 시간입니다.',
  },
  {
    id: 'fiba-shot-clock',
    question: 'FIBA 농구에서 기본 공격 제한 시간은?',
    answer: 24,
    unit: '초',
    category: '스포츠',
    explanation: 'FIBA 공식 장비·경기 규칙에 따른 기본 샷클록 시간입니다.',
  },
  {
    id: 'fiba-3x3-shot-clock',
    question: 'FIBA 3대3 농구의 공격 제한 시간은?',
    answer: 12,
    unit: '초',
    category: '스포츠',
    explanation: 'FIBA 3대3 공식 경기 규칙에 따른 공격 제한 시간입니다.',
  },
  {
    id: 'volleyball-team-hits',
    question: '실내 배구에서 한 팀이 블로킹을 제외하고 공을 넘기기 전까지 칠 수 있는 최대 횟수는?',
    answer: 3,
    unit: '회',
    category: '스포츠',
    explanation: '국제배구연맹 기본 규칙에 명시된 팀당 최대 접촉 횟수입니다.',
  },
  {
    id: 'table-tennis-net-height',
    question: '국제 규격 탁구 네트의 높이는?',
    answer: 15.25,
    unit: 'cm',
    category: '스포츠',
    explanation: '국제탁구연맹 경기 규칙에 명시된 네트 높이입니다.',
  },
  {
    id: 'table-tennis-ball-diameter',
    question: '국제 규격 탁구공의 지름은?',
    answer: 40,
    unit: 'mm',
    category: '스포츠',
    explanation: '국제탁구연맹 경기 규칙에 명시된 공의 지름입니다.',
  },
  {
    id: 'coca-cola-sugar-12oz',
    question: '미국 코카콜라 오리지널 12fl oz(약 355ml) 1캔에 든 당류는?',
    answer: 39,
    unit: 'g',
    category: '음식',
    explanation: '코카콜라 미국 공식 영양정보에 표시된 12fl oz 캔 1개 기준 당류입니다.',
  },
  {
    id: 'handball-court-length',
    question: '국제 규격 실내 핸드볼 코트의 세로 길이는?',
    answer: 40,
    unit: 'm',
    category: '스포츠',
    explanation: '국제핸드볼연맹 경기 규칙의 40m × 20m 코트 규격입니다.',
  },
  {
    id: 'futsal-goal-width',
    question: 'FIFA 풋살 골대의 안쪽 너비는?',
    answer: 3,
    unit: 'm',
    category: '스포츠',
    explanation: 'FIFA 풋살 경기 규칙이 정한 골대 너비입니다.',
  },
  {
    id: 'baseball-pitching-distance',
    question: 'MLB 투수판 앞쪽에서 홈플레이트 뒤쪽 끝까지 거리는 약 얼마일까?',
    answer: 18.44,
    unit: 'm',
    category: '스포츠',
    explanation: 'MLB 규칙의 60피트 6인치를 미터로 환산한 값입니다.',
  },
  {
    id: 'golf-hole-diameter',
    question: '골프 홀의 공식 지름은?',
    answer: 108,
    unit: 'mm',
    category: '스포츠',
    explanation: 'R&A 골프 규칙에 명시된 4.25인치의 미터법 표기입니다.',
  },
  {
    id: 'badminton-net-post-height',
    question: '배드민턴 네트 기둥의 공식 높이는?',
    answer: 1.55,
    unit: 'm',
    category: '스포츠',
    explanation: '세계배드민턴연맹 경기 규칙에 명시된 기둥 높이입니다.',
  },
  {
    id: 'oscar-statuette-weight',
    question: '아카데미 시상식 오스카 트로피의 무게는 약 얼마일까?',
    answer: 3.86,
    unit: 'kg',
    category: '문화',
    explanation: '미국 영화예술과학아카데미가 공개한 8.5파운드를 환산한 값입니다.',
  },
  {
    id: 'world-cup-trophy-weight',
    question: 'FIFA 월드컵 우승 트로피의 무게는?',
    answer: 6.175,
    unit: 'kg',
    category: '스포츠',
    explanation: 'FIFA가 공개한 18캐럿 금 트로피의 공식 무게입니다.',
  },
  {
    id: 'modern-piano-keys',
    question: '현대 표준 피아노의 건반은 모두 몇 개일까?',
    answer: 88,
    unit: '개',
    category: '문화',
    explanation: '흰 건반 52개와 검은 건반 36개를 합한 표준 구성입니다.',
  },
  {
    id: 'periodic-table-elements',
    question: '현재 국제적으로 공인된 주기율표의 원소는 모두 몇 개일까?',
    answer: 118,
    unit: '개',
    category: '과학',
    explanation: 'IUPAC가 공인한 1번 수소부터 118번 오가네손까지의 개수입니다.',
  },
  {
    id: 'fat-calories-per-gram',
    question: '미국 FDA 영양표시 기준 지방 1g은 몇 kcal의 열량을 낼까?',
    answer: 9,
    unit: 'kcal',
    category: '음식',
    explanation: 'FDA 식품 표시 지침에서 사용하는 지방 1g당 열량 환산값입니다.',
  },
];
